"""Add cascade delete to user relationships

Revision ID: 74e6081b3a9f
Revises: 8fef35cdd37a
Create Date: 2024-08-02 13:49:21.308944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e6081b3a9f'
down_revision = '8fef35cdd37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.drop_constraint('business_profile_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chatbot_log', schema=None) as batch_op:
        batch_op.drop_constraint('chatbot_log_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.drop_constraint('testimonial_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('testimonial_request', schema=None) as batch_op:
        batch_op.drop_constraint('testimonial_request_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('testimonial_request_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('testimonial_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('chatbot_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chatbot_log_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('business_profile_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
