"""Force migration

Revision ID: 8fef35cdd37a
Revises: 
Create Date: 2024-08-02 11:48:20.459132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fef35cdd37a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=True,
               existing_nullable=False)

    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=True,
               existing_nullable=False)

    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=True,
               existing_nullable=False)

    with op.batch_alter_table('testimonial_request', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=True,
               existing_nullable=False)

    with op.batch_alter_table('chatbot_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=True,
               existing_nullable=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=True,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=False,
               existing_nullable=False)

    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=False,
               existing_nullable=False)

    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=False,
               existing_nullable=False)

    with op.batch_alter_table('testimonial_request', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=False,
               existing_nullable=False)

    with op.batch_alter_table('chatbot_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=False,
               existing_nullable=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               autoincrement=False,
               existing_nullable=False)

    # ### end Alembic commands ###

