"""Add review_url and review_button_text to BusinessProfile

Revision ID: c2cb85ece3cc
Revises: 0ae7c6324f88
Create Date: 2024-07-29 14:10:04.222989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cb85ece3cc'
down_revision = '0ae7c6324f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('review_button_text', sa.String(length=100), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('testimonial_approval_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('testimonial_approval_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.drop_column('review_button_text')
        batch_op.drop_column('review_url')

    # ### end Alembic commands ###
