"""Add website_quote and headline to testimonial model

Revision ID: dd315838e07b
Revises: ee27a994790e
Create Date: 2024-07-30 12:33:17.309026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd315838e07b'
down_revision = 'ee27a994790e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_quote', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('headline', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.drop_column('headline')
        batch_op.drop_column('website_quote')

    # ### end Alembic commands ###
