"""Add is_displayed Boolean

Revision ID: ee27a994790e
Revises: c2cb85ece3cc
Create Date: 2024-07-30 09:49:58.970631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee27a994790e'
down_revision = 'c2cb85ece3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_displayed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.drop_column('is_displayed')

    # ### end Alembic commands ###
